# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#
# Site setting
title: Dongdong's  blog
SEOTitle: 东东的博客
header-img: img/baobao.jpeg
email: zhangyidong42@126.com
description: >- # this means to ignore newlines until "baseurl:"
    Take notes
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zhydong.github.io" 

# Sidebar settings
sidebar: true
sidebar-about-description: "I love yanyan"
sidebar-avatar: /img/baobao.jpeg

# SNS setting
RSS: false
twitter_username: digitalbiscuitz
github_username: zhydong
weibo_username: digitalbiscuitz

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
